### ISSUE TITLE
Downloaded file does not show up on the website

### ISSUE THREAD

**Issue by anarwal** [rdilweb/docusaurus-plugin-remote-content#28] opened 2022-01-09 13:53 UTC
Using the plugin I was successfully able to download the file in my project's directory, however file does not show up on my `docusarus` website until I stop and restart the app. Is it not possible to automatically update the website after downloading the file?

**Comment by RDIL** [comment] 2022-01-09 16:52
Will be fixed along with #25 

Duplicate of #25

**Closed by RDIL** 2022-01-09 16:52 UTC
