### ISSUE TITLE
Git repository support

### ISSUE THREAD

**Issue by selankon** [rdilweb/docusaurus-plugin-remote-content#50] opened 2022-11-25 08:48 UTC
Is there a way to give Github support to this plugin?

What I mean is to download folders from a specific git repository. Now the only way to get remote content is that this content is already deployed, so if I just want to get the .md files from a specific directory on a git repo I can't.

A workaround for this is a script that clone the repo locally and get the files, for example?

Thanks in advance

**Comment by RDIL** [comment] 2022-12-02 16:52
Duplicate of https://github.com/rdilweb/docusaurus-plugin-remote-content/issues/37

**Closed by RDIL** 2022-12-02 16:52 UTC
