### ISSUE TITLE
Downloading of images does not work

### ISSUE THREAD

**Issue by eric-gonzalez-tfs** [rdilweb/docusaurus-plugin-remote-content#47] opened 2022-11-02 21:02 UTC
First off, thanks for writing this package!

The repo I am trying to access has images referenced in the markdown. I tried to download the files using the basic configuration but the files that end up getting written are corrupted.

![Screen Shot 2022-11-02 at 1 51 44 PM](https://user-images.githubusercontent.com/82120345/199601107-a3f73782-1135-4023-8f3b-398f395a4439.png)

I looked into the code and noticed that Axios is used under the hood. It is my understanding that [Axios' request options](https://github.com/rdilweb/docusaurus-plugin-remote-content/blob/256e3c04d72eeb431b7da4a548338a84f22b3279/src/index.ts#L142) must have `responseType` set to `stream`.

When adding this to my plugin configuration, I see the following error: 

![Screen Shot 2022-11-02 at 2 00 09 PM](https://user-images.githubusercontent.com/82120345/199601536-c5beb869-88d0-4f83-9c65-50a6aeb1ba7d.png)

I believe this is because it is being passed into [`writeFileSync`](https://github.com/rdilweb/docusaurus-plugin-remote-content/blob/256e3c04d72eeb431b7da4a548338a84f22b3279/src/index.ts#L169) as is.

Any ideas on how to get around this issue?

**Comment by RDIL** [comment] 2022-11-03 00:50
Duplicate of https://github.com/rdilweb/docusaurus-plugin-remote-content/discussions/44

**Closed by RDIL** 2022-11-03 00:50 UTC

**Comment by eric-gonzalez-tfs** [comment] 2022-11-03 01:01
> Duplicate of #44

@RDIL Oops - should’ve looked in closed issues. Appreciate the response.
