### ISSUE TITLE
`yarn start` rebuilds continuously

### ISSUE THREAD

**Issue by gotson** [rdilweb/docusaurus-plugin-remote-content#25] opened 2021-12-16 03:44 UTC
When using the plugin, and after running `yarn start`, the client rebuilds continuously. See video:

https://user-images.githubusercontent.com/2139133/146304493-30f60746-8e71-4347-a5f1-ed9bf3023170.mov

**Comment by RDIL** [comment] 2021-12-16 14:28
Hey @gotson, thanks for letting me know.  Can you share your config, so I can try to reproduce?  Or, if the repository is public, a link to it would also work.

Thank you!

**Comment by gotson** [comment] 2021-12-17 02:38
> Hey @gotson, thanks for letting me know. Can you share your config, so I can try to reproduce? Or, if the repository is public, a link to it would also work.
> 
> Thank you!

Hi, the repository is public, you can find it [here](https://github.com/anansi-project/anansi-project.github.io). It also pulls public files.

For the moment i set `noRuntimeDownloads: true,` to avoid the problem, you can try changing it to `false`. It doesn't always start looping straight away, but after changing some other unrelated files, it will.

**Comment by RDIL** [comment] 2021-12-19 01:15
Thanks for the heads up.  I'll take a look for you on Monday.

**Comment by RDIL** [comment] 2021-12-20 16:05
Alright, so the problem is that docusaurus doesn't support plugins that need to be async, so I'll try to handle this upstream.

**Comment by RDIL** [comment] 2022-01-06 19:15
At this point, there isn't really anything I can do.  Waiting on upstream (cc @Josh-Cena)

**Comment by Josh-Cena** [comment] 2022-01-06 23:13
Hey, plugins can now be asyncly inited, just waiting for the next release

**Comment by anarwal** [comment] 2022-01-27 17:35
@Josh-Cena I see there was a new release recently. Was the fix applied for this along with new release?

**Comment by RDIL** [comment] 2022-01-31 16:34
I'm going to see if I can get a release out in the next 2-3 days to fix this.

**Comment by RDIL** [comment] 2022-02-09 17:59
Alright, working on a fix for this now.  Sorry for the delay!

Regarding the fix, going to link here in the code for anybody that reaches the error message that states the content didn't get downloaded yet.  Either the download has failed, or the plugin was not `await`ed by Docusaurus (the ability to do this was introduced in v2.0.0-beta.15, so you need to be using this version or later).

**Closed** 2022-02-09 18:06 UTC
Labels: bug
